name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'doc/**'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build-wheel:
    name: Build Wheel for Python ${{ matrix.py }} on ${{ matrix.os }}
    uses: ./.github/workflows/build-workflow.yml
    strategy:
      fail-fast: false
      matrix:
        py: [3.10]
    with:
      py: ${{ matrix.py }}
