name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    paths:
      - '**.py'
      - '**.pyi'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  lint_py:
    name: Lint Python
    uses: ./.github/workflows/lint-workflow.yaml