name: Lint and Type Check

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy flake8 black isort
          pip install .

      - name: Run mypy
        run: |
          mypy --install-types --non-interactive .
        continue-on-error: false

      - name: Run flake8
        run: |
          flake8 .
        continue-on-error: false

      - name: Run black
        run: |
          black --check .
        continue-on-error: false

      - name: Run isort
        run: |
          isort . --check-only
        continue-on-error: false
